#!/usr/bin/env bash

PROJECT_NAME="${1}"
TIMENOW="$(date '+%Y%m%d-%OH%OM%OS')"

# Init
mkdir -p "${DEV:-$HOME/workspace}/${PROJECT_NAME:-node-${TIMENOW}}"
cd "${DEV:-$HOME/workspace}/${PROJECT_NAME:-node-${TIMENOW}}"
yarn init -y
yarn add express
yarn add nodemon -D
# Libs
yarn add uuidv4
