#!/usr/bin/env bash

PROJECT_NAME="${1}"
TIMENOW="$(date '+%Y%m%d-%OH%OM%OS')"

# Init
mkdir -p "${DEV:-$HOME/workspace}/${PROJECT_NAME:-react-${TIMENOW}}"
cd "${DEV:-$HOME/workspace}/${PROJECT_NAME:-react-${TIMENOW}}"
mkdir public src
yarn init -y
yarn add react react-dom
yarn add @babel/core @babel/preset-env @babel/preset-react webpack webpack-cli
yarn add @babel/cli
yarn add babel-loader
yarn add webpack-dev-server -D
yarn add style-loader css-loader
yarn add file-loader
yarn add @babel/plugin-transform-runtime -D  ## for async/await etc.

# Libs
yarn add axios
